Lambda-School-Labs/allay-fe

- src/App.js
- src/components/Auth/Login.js
- src/components/Auth/Signup.js
- src/components/Dashboard/ReviewForm.js
- src/components/Dashboard/ReviewList.js
> set up some components to hold the forms

- package.json
- src/App.css
- src/components/Auth/Signup.js
- src/components/Dashboard/AddCompanyForm.js
- src/components/Dashboard/ReviewForm.js
Did refactoring from material to Chakra in the Add company component.
fixed issue with the cancel button.It now cancels properly.
> Company form refactor ap

- package.json
- src/App.js
- src/components/Auth/Login.js
- src/components/Auth/Signup.js
- src/components/Dashboard/NavBar.js
- src/components/Dashboard/ReviewForm.js
- src/index.js
Added initial setup of google analytics for PageView and some Events
> Google analytics ism

- src/components/Dashboard/SingleReview.js
Refactored to match the styles of chakra
end to end
> Refactor single review ap

- src/components/Dashboard/AddCompanyForm.js
- src/components/Dashboard/ReviewForm.js
- src/utils/axiosWithAuth.js
> Forms styling na

- src/components/Auth/Login.js
- src/components/Dashboard/NavBar.js
- src/components/Dashboard/SingleReview.js
refactor single review view, and fix recent posts header to make it dynamic
- [] Complete, but not tested (may need new tests)
> Update singleview sm

- package.json
- public/index.html
- src/App.js
- src/__tests__/App.test.js
- src/__tests__/Login.test.js
- src/__tests__/ReviewForm.test.js
- src/__tests__/Signup.test.js
- src/index.js
- src/store.js
moved redux store and implemented new React GA
> Redux testing ap

- README.md
> process_env added to readme

- package.json
- src/.github/workflows/ci.yml
- src/codeclimate.yml
> configured jest coverage, github actions and, github workflow config

- package.json
- src/components/Dashboard/ReviewForm.js
- src/state/reducers/companyReducer.js
- src/state/reducers/reviewReducer.js
Update reducers to include isLoading where it was missing.
> Update reducer wc

- src/components/Dashboard/DashboardHome.js
- src/components/Dashboard/NavBar.js
- src/components/Dashboard/SingleReview.js
Adds a search bar to the NavBar, which allows for filtering reviews by company name.
> Searchbar mw

- src/App.js
> fix node_env

- package.json
- src/App.css
- src/components/Dashboard/DashboardHome.js
- src/components/Dashboard/NavBar.js
- src/components/Dashboard/ReviewCard.js
> Refactor review card wc

- package.json
- src/App.css
- src/components/Dashboard/DashboardHome.js
- src/components/Dashboard/NavBar.js
- src/components/Dashboard/ReviewCard.js
Adds a modal window for displaying individual reviews on click from the review list. Still needs styling.
> Review modal styling mw

- package.json
- src/App.css
- src/components/Dashboard/DashboardHome.js
- src/components/Dashboard/NavBar.js
- src/components/Dashboard/ReviewCard.js
Reverts Lambda-School-Labs/allay-fe#25
> Revert "Review modal styling mw"

- src/components/Dashboard/DashboardHome.js
- src/components/Dashboard/NavBar.js
Fix display of no reviews message
> fixed no reviews message to match review card design

- src/App.js
- src/components/Dashboard/DashboardHome.js
- src/components/Dashboard/Forms/FormControler.js
- src/components/Dashboard/Forms/FormController.js
- src/components/Dashboard/Forms/InterviewForm.js
- src/components/Dashboard/Forms/ReviewForm2.js
- src/components/Dashboard/NavBar.js
- src/components/Dashboard/ReviewCard.js
- src/components/Dashboard/SingleReview.js
boilerplate for new forms and clean up files
> Interview form2 sm

- src/components/Dashboard/DashboardHome.js
- src/components/Dashboard/ReviewCard.js
Added the ability to highlight review cards on hover in the dashboard. also made various styling tweaks to review cards and dashboard, including stopping the navbar from hiding reviews and bugging out on browser resizing.
> Review card styling mw

- src/components/Dashboard/DashboardHome.js
- src/components/Dashboard/NavBar.js
- [x ] New feature (non-breaking change which adds functionality)
- [X ] This change requires a documentation update
- [X ] Complete, tested, ready to review and merge
- [X ] Tested manually
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] My changes generate no new warnings
- [X ] There are no merge conflicts
> Filter reviews refactor ism

- src/components/Dashboard/Forms/EditReviewForm.js
- src/components/Dashboard/ReviewCard.js
- src/state/actions/index.js
- src/state/actions/interviewReviewActions.js
- src/state/actions/reviewActions.js
Changes some routes in our reviewAction.js so the app does not crash on login. Restored the edit and delete functionality. Styled the dashboard a little more to match UX.
> New database refactor mw

- src/components/Dashboard/NavBar.js
Users can now logout from the site. When logging out from the dashboard, removes the JWT token and userId from localstorage and redirects to the login form.
> added logout functionality in the navbar

- src/components/Dashboard/CompanyReviewCard.js
- src/components/Dashboard/DashboardHome.js
Added some mobile responsiveness to the dashboard and individual cards. Everything stays neat and tidy, but could definitely use some more styling once we get UX designs for mobile.
> Mobile responsive dashboard

- src/components/Dashboard/Forms/EditReviewForm.js
- src/components/Dashboard/NavBar.js
- src/components/Dashboard/ReviewCard.js
Cards should all display the correct information, whether you are looking at a review card or interview card. Delete and Edit functionality restored.
> Dashboard card fix mw

- README.md
Update read me and remove all pre filled info
> remove all pre filled info

- src/components/Dashboard/DashboardHome.js
- src/components/Dashboard/Forms/AddCompanyForm.js
- src/components/Dashboard/Forms/EditInterviewForm.js
- src/components/Dashboard/ReviewCard.js
- src/components/Reusable/InputFields/EditReviewInput.js
making the app pixel perfect...ish
> Beautify app wc

- cypress/integration/login_test.js
- src/components/Auth/Login.js
> login test

- cypress/integration/company_review_test.js
test if a company review can be made
> finish company review test

- README.md
- cypress/integration/company_review_test.js
- cypress/integration/createInterviewReview_test.js
- src/components/Dashboard/DashboardHome.js
- src/components/Dashboard/Forms/CompanyReviewForm.js
- src/components/Dashboard/Forms/FormController.js
- src/components/Dashboard/Forms/InterviewForm.js
- src/components/Dashboard/NavBar.js
- src/components/Reusable/CompanySelect.js
Wrote test to login and create and post an interview review
> Testing wc

- README.md
- src/components/Auth/Signup.js
- src/store.js
> Remove devtools sm

- src/components/Auth/Login.js
- src/components/Dashboard/AdminButtons/BlockButton.js
- src/components/Dashboard/AdminButtons/ContentButton.js
- src/components/Dashboard/DashboardHome.js
- src/components/Dashboard/NavBar.js
- src/components/Dashboard/ReviewCard.js
- src/state/actions/authActions.js
- src/state/actions/reviewActions.js
- src/state/reducers/authReducer.js
> Admin functions sd

- src/components/Auth/Login.js
- src/components/Dashboard/AdminButtons/BlockButton.js
- src/components/Dashboard/AdminButtons/ContentButton.js
- src/components/Dashboard/DashboardHome.js
- src/components/Dashboard/ReviewCard.js
- src/state/actions/reviewActions.js
> Admin buttons

- package.json
updated and added to the package.json under scripts 
updated the package.json
> added coverage to package.json under scripts

- src/components/Dashboard/UserProfile/ProfilePage.js
- [ x] New feature (non-breaking change which adds functionality)
- [x ] Complete, tested, ready to review and merge
- [ x] Test A
- [ x] My code follows the style guidelines of this project
- [x ] I have commented my code, particularly in hard-to-understand areas
- x[x ] My changes generate no new warnings
- [x ] There are no merge conflicts
> update user page

- src/components/Auth/Signup-Additional.js
- src/components/Dashboard/UserProfile/ProfilePage.js
> add tooltip

- src/components/Auth/Signup-Additional.js
- src/components/Auth/Signup.js
- src/components/Reusable/InputFields/Autocomplete.js
> Signup functionality sd

- src/components/Auth/Signup-Additional.js
- src/components/Auth/Signup.js
- src/components/Dashboard/UserProfile/ProfilePage.js
- src/state/actions/authActions.js
- src/state/actions/userActions.js
update signup form with cloudinary functionality
> Signup form

- src/components/Auth/Signup-Additional.js
- src/components/Auth/Signup.js
- src/components/Dashboard/UserProfile/EditUserProfile.js
- src/state/actions/index.js
- src/state/actions/userActions.js
- src/state/reducers/userReducer.js
- src/state/types/index.js
made edit User page functional
was not functional before
> Edituserprofile

- src/components/Auth/Signup.js
- src/components/Dashboard/NavBar.js
- src/components/Dashboard/UserProfile/EditUserProfile.js
- src/components/Dashboard/UserProfile/ProfilePage.js
- src/state/actions/authActions.js
- src/state/actions/userActions.js
- src/state/reducers/userReducer.js
final touches to user profile page
> User profile finale

- package-lock.json
- package.json
- src/App.js
update Google Analytics ID
needed to be updated from old ID
> update google analytics ID number

- .eslintrc.js
- .prettierrc.js
- README.md
- package-lock.json
- package.json
I added a config file and settings for eslint and prettier so the whole team can have the same syntax. Result: cleaner code
Added config files
> added config file and settings for eslint and prettier

- cypress/integration/admin_bind_button_test.js
- cypress/integration/admin_delete_button_test.js
- cypress/integration/admin_login_test.js
- cypress/integration/company_review_test.js
- cypress/integration/createInterviewReview_test.js
- cypress/integration/delete_test.js
- cypress/integration/editInterview_test.js
- cypress/integration/editReview_test.js
- cypress/integration/login_test.js
- cypress/integration/logout_test.js
- cypress/integration/searchBar_test.js
- cypress/integration/updateUserProfile_test.js
- cypress/integration/userProfile_test.js
- cypress/support/commands.js
- package-lock.json
- package.json
Refactored the fe tests to use new login command.
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] Complete, tested, ready to review and merge
- [x ] Cypress
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] My code has been reviewed by at least one peer
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [ x] There are no merge conflicts
> Testing refactor sd

- src/components/Dashboard/UserProfile/ProfilePageReview.js
extract date logic for user profile into a function
> extract the date logic into a function

- README.md
debugged Readme.md issue
markdown change
> centered dev names and links

- package-lock.json
- package.json
- src/components/Dashboard/NavBar.js
- src/components/Dashboard/ReviewCard.js
add relative time for review cards
- [x ] New feature (non-breaking change which adds functionality)
> added relative time

- src/components/Dashboard/NavBar.js
remove hamburger menu and replace with dropdown menu, put radio buttons in drop down menus, and change formatting to match figma file
> Navbar mandi

- src/components/Dashboard/DashboardHome.js
- src/components/Dashboard/NavBar.js
- src/components/Dashboard/UserProfile/EditUserProfile.js
- src/components/Dashboard/UserProfile/ProfilePage.js
correct drop down menu functionality for review types and fields
drop down menus were not selecting fields correctly
> fix drop down menus to make them select correctly

- src/components/Dashboard/NavBar.js
make search bar on dashboard case insensitive when searching for companies
was not case insensitive
> make search bar case insensitive

- package-lock.json
- package.json
- src/App.js
- src/components/Auth/Signup-Additional.js
- src/components/Dashboard/AdminButtons/BlockButton.js
- src/components/Dashboard/DashboardHome.js
- src/components/Dashboard/NavBar.js
- src/components/Dashboard/ReviewCard.js
- src/components/Dashboard/UserProfile/EditUserProfile.js
- src/components/Dashboard/UserProfile/ProfilePage.js
- src/components/Dashboard/UserProfile/ProfilePageReview.js
errors appearing in console and there was a lag in the profile image on the dashboard when a user went from another person's profile page back to the dashboard
> fix warnings an err

- src/components/Dashboard/Forms/CompanyReviewForm.js
- src/components/Dashboard/Forms/FormController.js
- src/components/Dashboard/Forms/InterviewForm.js
update top progress bar and company name input to capitalized first letter
progress bar used to give percent not completed instead of percent completed. Company name needs to start with a capital letter to be identified in company list
> update progress bar and change company name capitalization

- src/components/Dashboard/ReviewCard.js
> fixed user ability to delete own reviews

- .eslintrc.js
> fixes end of line and prop type false eslint errors

- src/components/Dashboard/Forms/CompanyReviewForm.js
- src/components/Dashboard/Forms/InterviewForm.js
Update form with buttons to prevent timing out error. Decrease time lag between questions
form would go blank if didn't enter information quickly enough
> Review forms2

- src/components/Dashboard/NavBar.js
- src/components/Dashboard/UserProfile/EditUserProfile.js
- src/components/Dashboard/UserProfile/ProfilePage.js
Fixes various styles on the dashboard and navbar
> Navbar dashb styles sd

- src/App.css
- src/components/Auth/Login.js
- src/components/Dashboard/Forms/CompanyReviewForm.js
- src/components/Dashboard/Forms/FormController.js
- src/components/Dashboard/Forms/InterviewForm.js
- src/components/Dashboard/Forms/ProgressHeader.js
- src/components/Reusable/ProgressBar.js
refactor forms to create a ProgressHeader component to prevent code duplication. Also restyled review forms to match design UX designer provided.
> Review form styling and refactoring

- src/components/Dashboard/Forms/CompanyReviewForm.js
- src/components/Dashboard/Forms/InterviewForm.js
- src/components/Dashboard/Forms/ProgressHeader.js
clock on progress bar was not updating
clock now updates time
> make progress bar clock functional again
